const INTERACTION_TYPES = {
  SIGNUP: 'SIGNUP',
  ADD_FRIEND: 'ADD_FRIEND',
  NFT_REDEEM: 'NFT_REDEEM',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
};

const INTERACTION_POINTS = {
  SIGNUP: 50,
  ADD_FRIEND: 10,
  NFT_REDEEM: 100,
  REFERRAL_BONUS: 30,
};

export { INTERACTION_TYPES, INTERACTION_POINTS };
